server:
  port: ${SERVER-PORT:8081}
spring:
  datasource:
    url: jdbc:postgresql://${DATABASE-HOST:localhost}:${DATABASE-PORT:5432}/${DATABASE-NAME:database}
    username: ${DATABASE-USER:postgres}
    password: ${DATABASE-PASSWORD:user}
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
  flyway:
    locations: classpath:migrations

